---
title: "Is College A Scam? : The Effects of College Education on the lives of Latinos"
author: "Sofia Garcia"
date: "2026-02-05"
output: html_document
cache_table: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("matrixStats", type = "binary")
library(matrixStats)
library(dplyr)
library(tidycensus)
library(tidyverse)
census_api_key("1d4b88243f284bec796dcd6d10489d5698ccae33", install=TRUE, overwrite=TRUE)

readRenviron("~/.Renviron")
```


```{r setup, include=FALSE}
#starts working on pulling data here 
states <- c('CA', 'TX', 'NY')

#using pums data to do comparisons I want
pumsdat <- get_pums(variables = c('AGEP', 'HISP', 'SCHL', 'PINCP', 'ST', 'PWGTP', 'HINS1', 'HINS2', 'HINS3', 'FS', 'OCCP'), state = states, survey = 'acs5', year = 2023)
pumsdat <- pumsdat %>% mutate(priv = ifelse(HINS1 == 1, 1, 0), pub = ifelse(HINS2 == 1 | HINS3 == 1, 1, 0), none = ifelse(HINS1 != 1 & HINS2 != 1 & HINS3 != 1, 1, 0))
pumsdat <- pumsdat %>% mutate(cache_table = TRUE)

#filtering Latino adults and education
latinos <- pumsdat %>% filter(HISP != 1, AGEP >= 25)
latedu <- latinos %>%
  mutate(
    college = ifelse(SCHL >= 21, 1, 0),
    PINCP = as.numeric(PINCP),
    PWGTP = as.numeric(PWGTP),

    priv = ifelse(HINS1 == 1, 1, 0),
    pub = ifelse(HINS2 == 1 | HINS3 == 1, 1, 0),
    none = ifelse(HINS1 != 1 & HINS2 != 1 & HINS3 != 1, 1, 0),

    receiving = ifelse(FS == 1, 1, 0),

    occ_cat = case_when(
      OCCP >= 10 & OCCP < 1000 ~ "Management",
      OCCP >= 1000 & OCCP < 2000 ~ "Business/Finance",
      OCCP >= 2000 & OCCP < 3000 ~ "STEM",
      OCCP >= 3000 & OCCP < 4000 ~ "Education/Legal",
      OCCP >= 4000 & OCCP < 5000 ~ "Healthcare",
      OCCP >= 5000 & OCCP < 7000 ~ "Service",
      OCCP >= 7000 & OCCP < 9000 ~ "Construction/Production",
      TRUE ~ "Other"
    )
  )
occ_compare <- latedu %>% group_by(college, occ_cat) %>% summarise(pop = sum(PWGTP, na.rm = TRUE), .groups = "drop") %>% group_by(college) %>% mutate(percent = pop / sum(pop))

latedu$college <- ifelse(latedu$SCHL >= 21, 1, 0)
#adding indicators to make regressions easier to run later 

#pulls education attainment by state(% of college v. non college latinos)
latedu <- latedu %>%
  mutate(
    PINCP = as.numeric(PINCP),
    PWGTP = as.numeric(PWGTP))
stedu <- latedu %>% group_by(STATE, college) %>% summarise(pop = sum(PWGTP, na.rm = TRUE), .groups = "drop") %>% group_by(STATE) %>% mutate(percent = pop / sum(pop))

#pulls a median income by state and education
stin <- latedu %>% group_by(STATE, college) %>% summarise(median_income = weightedMedian(PINCP, w = PWGTP, na.rm = TRUE), .groups = "drop")


#using PUMS data I can do the comparisons I want so I rewrote what I did with this data instead of tidycensus 
#using weighted data as it's more accurate of the whole population; PUMS pulls a sample of the data which could bias my results 
#ST codes: 08-CA, 48-TX, 36-NY
#PINCP: personal income; SCHL >= 21 is bachelors or higher
```

```{r}
#doing more variables here for organization

#health insurance 

healthin <- latedu %>%
  group_by(STATE, college) %>%
  summarise(
    priv = weighted.mean(priv, PWGTP, na.rm = TRUE),
    pub = weighted.mean(pub, PWGTP, na.rm = TRUE),
    none = weighted.mean(none, PWGTP, na.rm = TRUE),
    .groups = "drop")

#SNAP/gov assistance

snap <- latedu %>%
  group_by(STATE, college) %>%
  summarise(
    totalpop = sum(PWGTP, na.rm = TRUE),
    receiving = sum(receiving * PWGTP, na.rm = TRUE) / totalpop,
    .groups = "drop"
  )

snapcount <- latedu %>%
  group_by(STATE, college) %>%
  summarise(
    totalpop       = sum(PWGTP, na.rm = TRUE),              
    receiving_ct   = sum(receiving * PWGTP, na.rm = TRUE), 
    recprop        = receiving_ct / totalpop,              
    .groups        = "drop"
  )

```


```{r setup, include = FALSE}
#regressions 

#median income regression(linear)
inreg <- lm(PINCP ~ college + AGEP + factor(STATE), data = latedu, weights = PWGTP)
#summary(inreg)
#summary(inreg)$adj.r.squared

#health insurance regression(logistic)
privreg <- glm(priv ~ college + AGEP + factor(STATE), data = latedu, weights = PWGTP, family = binomial())
#summary(privreg)
#exp(coef(privreg))

pubreg <- glm(pub ~ college + AGEP + factor(STATE), data = latedu, weights = PWGTP, family = binomial())
#summary(pubreg)

#SNAP/gov assistance 
snapreg <- glm(receiving ~ college + AGEP + factor(STATE), data = latedu, weights = PWGTP, family = binomial())
#summary(snapreg)
#used receiving instead of snap because snap is grouped and for regressions we run them on individual observations (receiving is an individual level variable)

#occupation
occreg <- lm(PINCP ~ college + occ_cat + AGEP + factor(STATE), data = latedu, weights = PWGTP)
#summary(occreg)

#cross validation
library(caret)
set.seed(123)

train_control <- trainControl(method = "cv", number = 5)
cv_model <- train(PINCP ~ college + AGEP + factor(STATE), data = latedu, method = "lm", trControl = train_control, weights = PWGTP)
cv_model

library(car)
vif(inreg)
#vif <5 is good, vif 5-10 moderate concern, vif > 10 is problem: should tell me how much colinearity is bugging my model if at all(shouldn't be higher than 8)

#residual check: helps say my model assumptions are valid
latedu$log_income <- log(latedu$PINCP + 1)

lm(log_income ~ college + AGEP + factor(STATE), data = latedu)
plot(inreg, which = 1) 

# to dos in this section
# add specific columns in iterations; start with simple model that i can explain to everyone; to improve r^2
# cleft test for standard deviation; may be significant but not reproducible 
# come up with hypothesis
```

```{r}
#visualizations
library(ggplot2)
#median income graph
ggplot(stin, aes(x = STATE, y = median_income, fill = factor(college))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Median Income of Latino Adults by Education and State",
    x = "State",
    y = "Median Income",
    fill = "Education Level"
  ) +
  scale_fill_manual(
    labels = c("No College Degree", "College Degree"),
    values = c("#F8766D", "#00BFC4")
  ) + 
  scale_x_discrete(labels = c("06" = "CA", "36" = "NY", "48" = "TX")) +
  theme_minimal()

#healthcare graph 
ggplot(healthin, aes(x = STATE, y = priv, fill = factor(college))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Private Health Insurance Coverage Among Latino Adults",
    x = "State",
    y = "Percent with Private Insurance",
    fill = "Education Level"
  ) +
  scale_fill_manual(
    labels = c("No College Degree", "College Degree"),
    values = c("#F8766D", "#00BFC4")
  ) + 
  scale_y_continuous(labels = scales::percent)
  theme_minimal()

#snap graph 
ggplot(snap, aes(x = STATE, y = receiving, fill = factor(college))) + geom_bar(stat = "identity", position = "dodge") + labs(title = "SNAP Participation Among Latino Adults", x= "State", y = "Percent Receiving SNAP", fill = "Education Level") +
  scale_y_continuous(labels = scales::percent)   + theme_minimal()
\
#occupation graph
ggplot(occ_compare, aes(x = occ_cat, y = percent, fill = factor(college))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Occupations of Latino Adults by Education Level",
    x = "Occupation Category",
    y = "Percent of Population",
    fill = "Education"
  ) +
  scale_fill_manual(
    labels = c("No College Degree", "College Degree"),
    values = c("#F8766D", "#00BFC4")
  ) + scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#results are interpreted like 20% of latinos with a college degree work in construction, and 50% of latinos without a college degree work in construction
#more specifically "Among latino adults with a college degree, 20% work in construction, compared with 50% among those without a college degree
```

```{r}
#interpretations of linear regressions 
#inreg
# latino college grads earn an estimated 47,480.49 more than latino non college grads, age and state are held constant
# p value indicated findings were statistically significant: college education for latinos without a doubt has an impact on income outcomes that 
#other things to consider: age28 indicates that latino college grads at age 28 earn 7595.61 more than other 28 yr old latinos who didn't attend college, this is important when considering this is an age people tend to start families and family is an important factor within latino culture
#multiple r squared: 0.1812 indicates moderate explanatory power

#privreg
# p value < 0.5 meaning that results are statistically signficant
# latino college grads have ~ 2.5 times higher odds of having private health insurance compared to latino non college grads when controlling for state and age
# as latinos get older their likelihood of having private health insurance increases(increase starts at age 30 and keeps increasing)
# education increases access to private heathcare among Latino adults(but sure this is applicable to other ethnicities and races)

#pubreg
# p value indicates statistically significant results
# as age increases the likelihood of latinos with a college education having public healthcare decreases but increases around age 65 which is the age people typically get on medicare

#snapreg
# p value indicated statistically significant results 
# college educated latinos are less likely to be recieving snap benefits compared to latinos who don't have a college education
#occreg
# p values indicate statistically significant results 
# moderate explanatory power indicated by multiple r squared : 0.1955

#plot results (income)
#evidence of heteroskedasticity; as the variance of residuals increased with higher predicted income levels
#suggests model performs less consistently for higher income people and the outlier indicates that some observations weren't well explained by the model however despite the limitations, no severe non linear patterns were observered meaning that the linear specification is broadly appropriate 

#plot results (for income) post 
#college coef ~ 1.29 meaning 2.5-3 times higher income so latinos who have a college degree earn dramatically more than those without one
```

```{r}
#extra graph combining gov assistance, median income and priv health insurance

loutcomes <- latedu %>%
  group_by(college) %>%
  summarise(
    median_income = weightedMedian(PINCP, w = PWGTP, na.rm = TRUE),
    private_insurance = weighted.mean(priv, PWGTP, na.rm = TRUE),
    gov_assistance = weighted.mean(receiving, PWGTP, na.rm = TRUE),
    .groups = "drop"
  )

library(tidyr)

loutcomes_long <- loutcomes %>%
  pivot_longer(
    cols = c(median_income, private_insurance, gov_assistance),
    names_to = "outcome",
    values_to = "value"
  )

ggplot(loutcomes_long, aes(x = outcome, y = value, fill = factor(college))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Livelihood Outcomes of Latino Adults by Education",
    x = "Outcome",
    y = "Value",
    fill = "Education"
  ) +
  scale_fill_manual(
    labels = c("No College Degree", "College Degree"),
    values = c("#F8766D", "#00BFC4")
  ) +
  theme_minimal()

#to do this week: 
# make sure snap and insurance columns show up 
# make sure regressions are done well incase im asked about it
```

